/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\model\chessModel.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Hero=(props)=> {
  const { nodes, materials } = useGLTF('./model/chessModel.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.ground.geometry} material={materials.wood} />
      <mesh geometry={nodes.Plane080.geometry} material={materials.BoardMat_1} />
      <mesh geometry={nodes.Plane080_1.geometry} material={materials.BoardMat_2} />
      <mesh geometry={nodes.bishop011.geometry} material={materials.BoardMat_1} position={[-0.076, 0.01, -0.178]} />
      <mesh geometry={nodes.bishop012.geometry} material={materials.BoardMat_1} position={[0.076, 0.01, -0.178]} />
      <mesh geometry={nodes.horse011.geometry} material={materials.BoardMat_1} position={[0.127, 0.01, -0.178]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Plane076.geometry} material={materials.BoardMat_1} position={[0, 0.032, 0]} />
      </mesh>
      <mesh geometry={nodes.horse012.geometry} material={materials.BoardMat_1} position={[-0.127, 0.01, -0.178]} rotation={[0, 1.571, 0]}>
        <mesh geometry={nodes.Plane077.geometry} material={materials.BoardMat_1} position={[0, 0.032, 0]} />
      </mesh>
      <mesh geometry={nodes.king_007.geometry} material={materials.BoardMat_1} position={[-0.025, 0.01, -0.178]}>
        <mesh geometry={nodes.Circle007.geometry} material={materials.BoardMat_1} />
      </mesh>
      <mesh geometry={nodes.pawn035.geometry} material={materials.BoardMat_1} position={[-0.178, 0.01, -0.127]} />
      <mesh geometry={nodes.pawn036.geometry} material={materials.BoardMat_1} position={[-0.127, 0.01, -0.127]} />
      <mesh geometry={nodes.pawn037.geometry} material={materials.BoardMat_1} position={[-0.076, 0.01, -0.127]} />
      <mesh geometry={nodes.pawn038.geometry} material={materials.BoardMat_1} position={[-0.025, 0.01, -0.127]} />
      <mesh geometry={nodes.pawn039.geometry} material={materials.BoardMat_1} position={[0.025, 0.01, -0.127]} />
      <mesh geometry={nodes.pawn040.geometry} material={materials.BoardMat_1} position={[0.076, 0.01, -0.127]} />
      <mesh geometry={nodes.pawn041.geometry} material={materials.BoardMat_1} position={[0.127, 0.01, -0.127]} />
      <mesh geometry={nodes.pawn042.geometry} material={materials.BoardMat_1} position={[0.178, 0.01, -0.127]} />
      <mesh geometry={nodes.queen007.geometry} material={materials.BoardMat_1} position={[0.025, 0.01, -0.178]} />
      <mesh geometry={nodes.rook011.geometry} material={materials.BoardMat_1} position={[-0.178, 0.01, -0.178]} />
      <mesh geometry={nodes.rook012.geometry} material={materials.BoardMat_1} position={[0.178, 0.01, -0.178]} />
      <mesh geometry={nodes.bishop013.geometry} material={materials.BoardMat_2} position={[0.076, 0.01, 0.177]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.bishop014.geometry} material={materials.BoardMat_2} position={[-0.076, 0.01, 0.177]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.horse013.geometry} material={materials.BoardMat_2} position={[-0.127, 0.01, 0.177]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Plane078.geometry} material={materials.BoardMat_2} position={[0, 0.032, 0]} />
      </mesh>
      <mesh geometry={nodes.horse014.geometry} material={materials.BoardMat_2} position={[0.127, 0.01, 0.177]} rotation={[0, -1.571, 0]}>
        <mesh geometry={nodes.Plane079.geometry} material={materials.BoardMat_2} position={[0, 0.032, 0]} />
      </mesh>
      <mesh geometry={nodes.king_008.geometry} material={materials.BoardMat_2} position={[-0.025, 0.01, 0.178]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Circle008.geometry} material={materials.BoardMat_2} />
      </mesh>
      <mesh geometry={nodes.pawn043.geometry} material={materials.BoardMat_2} position={[-0.178, 0.01, 0.127]} />
      <mesh geometry={nodes.pawn044.geometry} material={materials.BoardMat_2} position={[-0.127, 0.01, 0.127]} />
      <mesh geometry={nodes.pawn045.geometry} material={materials.BoardMat_2} position={[-0.076, 0.01, 0.127]} />
      <mesh geometry={nodes.pawn046.geometry} material={materials.BoardMat_2} position={[-0.025, 0.01, 0.127]} />
      <mesh geometry={nodes.pawn047.geometry} material={materials.BoardMat_2} position={[0.025, 0.01, 0.127]} />
      <mesh geometry={nodes.pawn048.geometry} material={materials.BoardMat_2} position={[0.076, 0.01, 0.127]} />
      <mesh geometry={nodes.pawn049.geometry} material={materials.BoardMat_2} position={[0.127, 0.01, 0.127]} />
      <mesh geometry={nodes.pawn050.geometry} material={materials.BoardMat_2} position={[0.178, 0.01, 0.127]} />
      <mesh geometry={nodes.queen008.geometry} material={materials.BoardMat_2} position={[0.025, 0.01, 0.178]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.rook013.geometry} material={materials.BoardMat_2} position={[0.178, 0.01, 0.177]} rotation={[Math.PI, 0, Math.PI]} />
      <mesh geometry={nodes.rook014.geometry} material={materials.BoardMat_2} position={[-0.178, 0.01, 0.177]} rotation={[Math.PI, 0, Math.PI]} />
    </group>
  )
}
export default Hero;
useGLTF.preload('./model/chessModel.glb')
