/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\model\house.glb 
Author: Michel Donze (https://sketchfab.com/mdonze)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/the-house-lost-at-sea-bdf8ea72acd946798e250067e576c70d
Title: The house lost at sea
*/

import React, { useEffect,useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

 const House=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model/house.glb')
  const { actions,names } = useAnimations(animations, group)
  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.008}>
          <group name="3da24f50391d4dc7b0fceaba7f4772dffbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="WindowLightGlow" position={[-373.6, 1563.08, 187.452]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="WindowLightGlow_WindowLightGlow_0" geometry={nodes.WindowLightGlow_WindowLightGlow_0.geometry} material={materials.WindowLightGlow} />
                </group>
                <group name="WindowLightRefl" position={[-338.761, -1548.933, 194.492]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="1" geometry={nodes['1'].geometry} material={materials.WindowLight} morphTargetDictionary={nodes['1'].morphTargetDictionary} morphTargetInfluences={nodes['1'].morphTargetInfluences} />
                </group>
                <group name="WindowLight" position={[-373.6, 1563.08, 187.452]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="WindowLight_WindowLight_0" geometry={nodes.WindowLight_WindowLight_0.geometry} material={materials.WindowLight} />
                </group>
                <group name="WindowLightTop" position={[-435.181, 1730.043, 221.298]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="WindowLightTop_WindowLight_0" geometry={nodes.WindowLightTop_WindowLight_0.geometry} material={materials.WindowLight} />
                </group>
                <group name="Fog" position={[-360.056, 0, -234.081]} rotation={[-Math.PI / 2, 0, -0.018]} scale={100}>
                  <mesh name="Fog_Mist_0" geometry={nodes.Fog_Mist_0.geometry} material={materials.Mist} />
                </group>
                <group name="Wave" position={[-63.069, 3.254, 643.307]} rotation={[-Math.PI / 2, 0, 0]} scale={[169.454, 169.917, 15.813]}>
                  <mesh name="Wave_Waves_0" geometry={nodes.Wave_Waves_0.geometry} material={materials.Waves} />
                </group>
                <group name="Wave001" position={[-63.069, 3.254, 643.307]} rotation={[-Math.PI / 2, 0, 0]} scale={[45.709, 45.709, 742.044]}>
                  <mesh name="Wave001_Waves_0" geometry={nodes.Wave001_Waves_0.geometry} material={materials.Waves} />
                </group>
                <group name="Wave002" position={[-63.069, 3.254, 643.307]} rotation={[-Math.PI / 2, 0, 0]} scale={[196.474, 195.781, 74.853]}>
                  <mesh name="Wave002_Waves_0" geometry={nodes.Wave002_Waves_0.geometry} material={materials.Waves} />
                </group>
                <group name="Wave003" position={[-63.069, 3.254, 643.307]} rotation={[-Math.PI / 2, 0, 0]} scale={[200.768, 201.933, 24.02]}>
                  <mesh name="Wave003_Waves_0" geometry={nodes.Wave003_Waves_0.geometry} material={materials.Waves} />
                </group>
                <group name="Wave001B" position={[-63.069, 3.254, 643.307]} rotation={[-Math.PI / 2, 0, 0]} scale={[389.348, 389.348, 742.044]}>
                  <mesh name="Wave001B_Waves_0" geometry={nodes.Wave001B_Waves_0.geometry} material={materials.Waves} />
                </group>
                <group name="particle000" position={[2483.349, 128.883, 1279.969]} rotation={[-Math.PI / 2, 0, 0]} scale={3.208}>
                  <mesh name="particle000_ParticleDustShdr_0" geometry={nodes.particle000_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle005" position={[-1098.111, 2937.434, 1668.761]} rotation={[-Math.PI / 2, 0, 0]} scale={4.478}>
                  <mesh name="particle005_ParticleDustShdr_0" geometry={nodes.particle005_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle006" position={[447.494, 2457.413, -1848.493]} rotation={[-Math.PI / 2, 0, 0]} scale={1.577}>
                  <mesh name="particle006_ParticleDustShdr_0" geometry={nodes.particle006_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle017" position={[-2462.267, 1104.682, 411.301]} rotation={[-Math.PI / 2, 0, 0]} scale={4.003}>
                  <mesh name="particle017_ParticleDustShdr_0" geometry={nodes.particle017_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle036" position={[-1147.253, 425.14, 1014.45]} rotation={[-Math.PI / 2, 0, 0]} scale={2.087}>
                  <mesh name="particle036_ParticleDustShdr_0" geometry={nodes.particle036_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle043" position={[1086.212, 88.229, -1682.347]} rotation={[-Math.PI / 2, 0, 0]} scale={3.776}>
                  <mesh name="particle043_ParticleDustShdr_0" geometry={nodes.particle043_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle044" position={[2656.208, 3138.981, -867.172]} rotation={[-Math.PI / 2, 0, 0]} scale={4.925}>
                  <mesh name="particle044_ParticleDustShdr_0" geometry={nodes.particle044_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle055" position={[557.469, 1007.601, 1075.977]} rotation={[-Math.PI / 2, 0, 0]} scale={4.982}>
                  <mesh name="particle055_ParticleDustShdr_0" geometry={nodes.particle055_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle060" position={[-1439.796, -137.958, -1702.289]} rotation={[-Math.PI / 2, 0, 0]} scale={2.955}>
                  <mesh name="particle060_ParticleDustShdr_0" geometry={nodes.particle060_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle064" position={[904.821, 2279.155, 3168.508]} rotation={[-Math.PI / 2, 0, 0]} scale={4.656}>
                  <mesh name="particle064_ParticleDustShdr_0" geometry={nodes.particle064_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle068" position={[-1034.625, 3163.265, -385.751]} rotation={[-Math.PI / 2, 0, 0]} scale={4.585}>
                  <mesh name="particle068_ParticleDustShdr_0" geometry={nodes.particle068_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle070" position={[107.646, 993.964, -1829.011]} rotation={[-Math.PI / 2, 0, 0]} scale={4.45}>
                  <mesh name="particle070_ParticleDustShdr_0" geometry={nodes.particle070_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle071" position={[-297.306, 1531.02, -1421.549]} rotation={[-Math.PI / 2, 0, 0]} scale={4.334}>
                  <mesh name="particle071_ParticleDustShdr_0" geometry={nodes.particle071_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle085" position={[-375.967, 1304.308, 2316.513]} rotation={[-Math.PI / 2, 0, 0]} scale={4.697}>
                  <mesh name="particle085_ParticleDustShdr_0" geometry={nodes.particle085_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle090" position={[-594.928, 2200.626, 2109.139]} rotation={[-Math.PI / 2, 0, 0]} scale={4.431}>
                  <mesh name="particle090_ParticleDustShdr_0" geometry={nodes.particle090_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle102" position={[2687.575, 1655.746, -710.028]} rotation={[-Math.PI / 2, 0, 0]} scale={0.576}>
                  <mesh name="particle102_ParticleDustShdr_0" geometry={nodes.particle102_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle131" position={[-1767.292, 2884.473, 1397.552]} rotation={[-Math.PI / 2, 0, 0]} scale={3.865}>
                  <mesh name="particle131_ParticleDustShdr_0" geometry={nodes.particle131_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle136" position={[-2129.975, 1117.157, -1487.575]} rotation={[-Math.PI / 2, 0, 0]} scale={0.226}>
                  <mesh name="particle136_ParticleDustShdr_0" geometry={nodes.particle136_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle141" position={[1572.026, 1666.105, 431.745]} rotation={[-Math.PI / 2, 0, 0]} scale={4.629}>
                  <mesh name="particle141_ParticleDustShdr_0" geometry={nodes.particle141_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle144" position={[50.345, 2.13, -1961.06]} rotation={[-Math.PI / 2, 0, 0]} scale={4.747}>
                  <mesh name="particle144_ParticleDustShdr_0" geometry={nodes.particle144_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle152" position={[315.728, 1969.753, -1999.936]} rotation={[-Math.PI / 2, 0, 0]} scale={2.788}>
                  <mesh name="particle152_ParticleDustShdr_0" geometry={nodes.particle152_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle155" position={[-2347.816, 1257.225, 137.223]} rotation={[-Math.PI / 2, 0, 0]} scale={1.86}>
                  <mesh name="particle155_ParticleDustShdr_0" geometry={nodes.particle155_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle170" position={[-290.675, 2469.751, -426.843]} rotation={[-Math.PI / 2, 0, 0]} scale={0.301}>
                  <mesh name="particle170_ParticleDustShdr_0" geometry={nodes.particle170_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle174" position={[2582.426, 396.142, 1591.846]} rotation={[-Math.PI / 2, 0, 0]} scale={2.859}>
                  <mesh name="particle174_ParticleDustShdr_0" geometry={nodes.particle174_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle175" position={[1199.152, 1865.587, 2100.017]} rotation={[-Math.PI / 2, 0, 0]} scale={3.512}>
                  <mesh name="particle175_ParticleDustShdr_0" geometry={nodes.particle175_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle180" position={[633.545, 2324.83, 2732.604]} rotation={[-Math.PI / 2, 0, 0]} scale={3.529}>
                  <mesh name="particle180_ParticleDustShdr_0" geometry={nodes.particle180_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle189" position={[-163.272, 2870.049, -1656.663]} rotation={[-Math.PI / 2, 0, 0]} scale={2.86}>
                  <mesh name="particle189_ParticleDustShdr_0" geometry={nodes.particle189_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle190" position={[1992.449, 2394.511, 262.57]} rotation={[-Math.PI / 2, 0, 0]} scale={2.482}>
                  <mesh name="particle190_ParticleDustShdr_0" geometry={nodes.particle190_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle195" position={[-237.012, 2224.636, 1825.603]} rotation={[-Math.PI / 2, 0, 0]} scale={3.297}>
                  <mesh name="particle195_ParticleDustShdr_0" geometry={nodes.particle195_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle197" position={[-2001.562, 1322.076, 1519.877]} rotation={[-Math.PI / 2, 0, 0]} scale={2.178}>
                  <mesh name="particle197_ParticleDustShdr_0" geometry={nodes.particle197_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle202" position={[2055.5, 469.322, 1084.868]} rotation={[-Math.PI / 2, 0, 0]} scale={0.88}>
                  <mesh name="particle202_ParticleDustShdr_0" geometry={nodes.particle202_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle216" position={[-673.811, 400.494, -1285.523]} rotation={[-Math.PI / 2, 0, 0]} scale={4.358}>
                  <mesh name="particle216_ParticleDustShdr_0" geometry={nodes.particle216_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle241" position={[-1888.334, 750.622, 1408.371]} rotation={[-Math.PI / 2, 0, 0]} scale={2.256}>
                  <mesh name="particle241_ParticleDustShdr_0" geometry={nodes.particle241_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle243" position={[2444.345, 2953.777, -1459.945]} rotation={[-Math.PI / 2, 0, 0]} scale={1.296}>
                  <mesh name="particle243_ParticleDustShdr_0" geometry={nodes.particle243_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle244" position={[-1277.198, 2947.929, 2209.546]} rotation={[-Math.PI / 2, 0, 0]} scale={0.226}>
                  <mesh name="particle244_ParticleDustShdr_0" geometry={nodes.particle244_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle248" position={[778.81, 2853.722, -912.101]} rotation={[-Math.PI / 2, 0, 0]} scale={2.03}>
                  <mesh name="particle248_ParticleDustShdr_0" geometry={nodes.particle248_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle266" position={[-718.363, 2537.098, -2120.701]} rotation={[-Math.PI / 2, 0, 0]} scale={1.758}>
                  <mesh name="particle266_ParticleDustShdr_0" geometry={nodes.particle266_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle273" position={[-475.58, 1114.857, -1368.465]} rotation={[-Math.PI / 2, 0, 0]} scale={3.741}>
                  <mesh name="particle273_ParticleDustShdr_0" geometry={nodes.particle273_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle285" position={[-2190.646, 1828.903, -62.738]} rotation={[-Math.PI / 2, 0, 0]} scale={4.488}>
                  <mesh name="particle285_ParticleDustShdr_0" geometry={nodes.particle285_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle299" position={[1940.56, 1380.203, 640.326]} rotation={[-Math.PI / 2, 0, 0]} scale={1.773}>
                  <mesh name="particle299_ParticleDustShdr_0" geometry={nodes.particle299_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle301" position={[2795.246, 248.215, 2326.23]} rotation={[-Math.PI / 2, 0, 0]} scale={1.267}>
                  <mesh name="particle301_ParticleDustShdr_0" geometry={nodes.particle301_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle303" position={[2267.376, 1149.62, 2743.99]} rotation={[-Math.PI / 2, 0, 0]} scale={3.128}>
                  <mesh name="particle303_ParticleDustShdr_0" geometry={nodes.particle303_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle306" position={[-1314.453, 550.53, 2911.231]} rotation={[-Math.PI / 2, 0, 0]} scale={1.049}>
                  <mesh name="particle306_ParticleDustShdr_0" geometry={nodes.particle306_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle309" position={[1918.003, 2897.311, -1836.097]} rotation={[-Math.PI / 2, 0, 0]} scale={0.45}>
                  <mesh name="particle309_ParticleDustShdr_0" geometry={nodes.particle309_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle312" position={[2340.198, 778.269, 764.672]} rotation={[-Math.PI / 2, 0, 0]} scale={4.28}>
                  <mesh name="particle312_ParticleDustShdr_0" geometry={nodes.particle312_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle318" position={[-2123.118, 1531.278, -1636.675]} rotation={[-Math.PI / 2, 0, 0]} scale={2.075}>
                  <mesh name="particle318_ParticleDustShdr_0" geometry={nodes.particle318_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle320" position={[2113.517, 2629.922, -1100.456]} rotation={[-Math.PI / 2, 0, 0]} scale={2.974}>
                  <mesh name="particle320_ParticleDustShdr_0" geometry={nodes.particle320_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle324" position={[-313.57, 226.095, -1821.377]} rotation={[-Math.PI / 2, 0, 0]} scale={3.554}>
                  <mesh name="particle324_ParticleDustShdr_0" geometry={nodes.particle324_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle329" position={[407.739, 2345.532, 2562.13]} rotation={[-Math.PI / 2, 0, 0]} scale={1.825}>
                  <mesh name="particle329_ParticleDustShdr_0" geometry={nodes.particle329_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle332" position={[2411.191, 3109.096, 1258.411]} rotation={[-Math.PI / 2, 0, 0]} scale={1.899}>
                  <mesh name="particle332_ParticleDustShdr_0" geometry={nodes.particle332_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle335" position={[-2305.085, 1415.892, 2091.777]} rotation={[-Math.PI / 2, 0, 0]} scale={0.529}>
                  <mesh name="particle335_ParticleDustShdr_0" geometry={nodes.particle335_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle341" position={[1538.808, 2413.467, 2071.212]} rotation={[-Math.PI / 2, 0, 0]} scale={4.722}>
                  <mesh name="particle341_ParticleDustShdr_0" geometry={nodes.particle341_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle345" position={[-1703.97, 2964.711, 2998.78]} rotation={[-Math.PI / 2, 0, 0]} scale={2.194}>
                  <mesh name="particle345_ParticleDustShdr_0" geometry={nodes.particle345_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle353" position={[2464.198, 1876.861, 732.171]} rotation={[-Math.PI / 2, 0, 0]} scale={4.542}>
                  <mesh name="particle353_ParticleDustShdr_0" geometry={nodes.particle353_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle371" position={[-2351.515, 3173.316, -620.292]} rotation={[-Math.PI / 2, 0, 0]} scale={4.812}>
                  <mesh name="particle371_ParticleDustShdr_0" geometry={nodes.particle371_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle374" position={[1602.186, 1678.117, 2841.131]} rotation={[-Math.PI / 2, 0, 0]} scale={4.386}>
                  <mesh name="particle374_ParticleDustShdr_0" geometry={nodes.particle374_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle380" position={[898.093, 1600.573, 2849.673]} rotation={[-Math.PI / 2, 0, 0]} scale={3.304}>
                  <mesh name="particle380_ParticleDustShdr_0" geometry={nodes.particle380_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle381" position={[-1379.604, 2184.802, 1401.568]} rotation={[-Math.PI / 2, 0, 0]} scale={4.747}>
                  <mesh name="particle381_ParticleDustShdr_0" geometry={nodes.particle381_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle384" position={[1001.47, 1931.567, -2227.063]} rotation={[-Math.PI / 2, 0, 0]} scale={0.755}>
                  <mesh name="particle384_ParticleDustShdr_0" geometry={nodes.particle384_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle385" position={[1666.476, 561.963, 532.685]} rotation={[-Math.PI / 2, 0, 0]} scale={3.287}>
                  <mesh name="particle385_ParticleDustShdr_0" geometry={nodes.particle385_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle399" position={[609.946, 2615.682, -78.89]} rotation={[-Math.PI / 2, 0, 0]} scale={0.61}>
                  <mesh name="particle399_ParticleDustShdr_0" geometry={nodes.particle399_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle401" position={[956.519, 2132.777, -96.969]} rotation={[-Math.PI / 2, 0, 0]} scale={0.106}>
                  <mesh name="particle401_ParticleDustShdr_0" geometry={nodes.particle401_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle411" position={[-2092.284, 2203.745, -478.932]} rotation={[-Math.PI / 2, 0, 0]} scale={2.646}>
                  <mesh name="particle411_ParticleDustShdr_0" geometry={nodes.particle411_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle412" position={[-2413.137, 2378.645, 1547.405]} rotation={[-Math.PI / 2, 0, 0]} scale={2.364}>
                  <mesh name="particle412_ParticleDustShdr_0" geometry={nodes.particle412_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle413" position={[-2398.074, 2971.718, 1697.481]} rotation={[-Math.PI / 2, 0, 0]} scale={4.209}>
                  <mesh name="particle413_ParticleDustShdr_0" geometry={nodes.particle413_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle417" position={[-556.09, 1177.451, 2341.756]} rotation={[-Math.PI / 2, 0, 0]} scale={1.743}>
                  <mesh name="particle417_ParticleDustShdr_0" geometry={nodes.particle417_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle430" position={[963.403, 1002.054, 898.308]} rotation={[-Math.PI / 2, 0, 0]} scale={3.956}>
                  <mesh name="particle430_ParticleDustShdr_0" geometry={nodes.particle430_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle441" position={[-2038.484, -51.203, 2534.207]} rotation={[-Math.PI / 2, 0, 0]} scale={4.845}>
                  <mesh name="particle441_ParticleDustShdr_0" geometry={nodes.particle441_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle449" position={[2394.47, 1683.539, -990.246]} rotation={[-Math.PI / 2, 0, 0]} scale={0.78}>
                  <mesh name="particle449_ParticleDustShdr_0" geometry={nodes.particle449_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle452" position={[-2184.552, 3059.553, -466.851]} rotation={[-Math.PI / 2, 0, 0]} scale={1.683}>
                  <mesh name="particle452_ParticleDustShdr_0" geometry={nodes.particle452_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle455" position={[-313.297, 2417.497, 1492.467]} rotation={[-Math.PI / 2, 0, 0]} scale={0.564}>
                  <mesh name="particle455_ParticleDustShdr_0" geometry={nodes.particle455_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle458" position={[-342.46, 2376.227, 1275.307]} rotation={[-Math.PI / 2, 0, 0]} scale={4.196}>
                  <mesh name="particle458_ParticleDustShdr_0" geometry={nodes.particle458_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle459" position={[-848.36, 2482.74, -1910.611]} rotation={[-Math.PI / 2, 0, 0]} scale={0.976}>
                  <mesh name="particle459_ParticleDustShdr_0" geometry={nodes.particle459_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle462" position={[-431.609, 1086.771, -269.242]} rotation={[-Math.PI / 2, 0, 0]} scale={0.609}>
                  <mesh name="particle462_ParticleDustShdr_0" geometry={nodes.particle462_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle463" position={[-1672.155, 2764.2, 1369.924]} rotation={[-Math.PI / 2, 0, 0]} scale={4.115}>
                  <mesh name="particle463_ParticleDustShdr_0" geometry={nodes.particle463_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle468" position={[1942.584, 2835.513, -258.127]} rotation={[-Math.PI / 2, 0, 0]} scale={2.293}>
                  <mesh name="particle468_ParticleDustShdr_0" geometry={nodes.particle468_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle471" position={[1039.342, 1232.075, 2063.104]} rotation={[-Math.PI / 2, 0, 0]} scale={1.335}>
                  <mesh name="particle471_ParticleDustShdr_0" geometry={nodes.particle471_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle480" position={[237.863, 1985.431, 2954]} rotation={[-Math.PI / 2, 0, 0]} scale={2.967}>
                  <mesh name="particle480_ParticleDustShdr_0" geometry={nodes.particle480_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle495" position={[-506.497, 1184.552, -1712.062]} rotation={[-Math.PI / 2, 0, 0]} scale={2.579}>
                  <mesh name="particle495_ParticleDustShdr_0" geometry={nodes.particle495_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle497" position={[838.726, 2200.952, -1675.306]} rotation={[-Math.PI / 2, 0, 0]} scale={2.126}>
                  <mesh name="particle497_ParticleDustShdr_0" geometry={nodes.particle497_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="particle499" position={[2563.735, 2997.997, 2719.215]} rotation={[-Math.PI / 2, 0, 0]} scale={4.504}>
                  <mesh name="particle499_ParticleDustShdr_0" geometry={nodes.particle499_ParticleDustShdr_0.geometry} material={materials.ParticleDustShdr} />
                </group>
                <group name="HouseMain" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="HouseMain_HouseShdr_0" geometry={nodes.HouseMain_HouseShdr_0.geometry} material={materials.HouseShdr} />
                  <mesh name="HouseMain_HouseSerreLinesShdr_0" geometry={nodes.HouseMain_HouseSerreLinesShdr_0.geometry} material={materials.HouseSerreLinesShdr} />
                  <mesh name="HouseMain_WindowsInsideShdr_0" geometry={nodes.HouseMain_WindowsInsideShdr_0.geometry} material={materials.WindowsInsideShdr} />
                  <mesh name="HouseMain_WindowGlassShdr_0" geometry={nodes.HouseMain_WindowGlassShdr_0.geometry} material={materials.WindowGlassShdr} />
                  <mesh name="HouseMain_WindowDarkInsideShdr_0" geometry={nodes.HouseMain_WindowDarkInsideShdr_0.geometry} material={materials.WindowDarkInsideShdr} />
                </group>
                <group name="WindowLightRoof" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="0" geometry={nodes['0'].geometry} material={materials.WindowLight} morphTargetDictionary={nodes['0'].morphTargetDictionary} morphTargetInfluences={nodes['0'].morphTargetInfluences} />
                </group>
                <group name="WindowLightChimney" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="2" geometry={nodes['2'].geometry} material={materials.WindowLight} morphTargetDictionary={nodes['2'].morphTargetDictionary} morphTargetInfluences={nodes['2'].morphTargetInfluences} />
                </group>
                <group name="Ground" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Ground_Ground_0" geometry={nodes.Ground_Ground_0.geometry} material={materials.Ground} />
                </group>
                <group name="Shrubs" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Shrubs_Shrubs_0" geometry={nodes.Shrubs_Shrubs_0.geometry} material={materials.Shrubs} />
                  <mesh name="Shrubs_Bushes_0" geometry={nodes.Shrubs_Bushes_0.geometry} material={materials.Bushes} />
                </group>
                <group name="DebrisOk" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="DebrisOk_Debris_0" geometry={nodes.DebrisOk_Debris_0.geometry} material={materials.Debris} />
                  <mesh name="DebrisOk_Debris_0_1" geometry={nodes.DebrisOk_Debris_0_1.geometry} material={materials.Debris} />
                </group>
                <group name="Sea" rotation={[-Math.PI / 2, 0, 0]} scale={85.543}>
                  <mesh name="Sea_Sea_0" geometry={nodes.Sea_Sea_0.geometry} material={materials.material} />
                </group>
                <group name="Sky" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Sky_Sky_0" geometry={nodes.Sky_Sky_0.geometry} material={materials.material_12} />
                </group>
                <group name="Bushesefl" rotation={[-Math.PI / 2, 0, Math.PI]} scale={-100}>
                  <mesh name="Bushesefl_BushesRefl_0" geometry={nodes.Bushesefl_BushesRefl_0.geometry} material={materials.BushesRefl} />
                  <mesh name="Bushesefl_ShrubsRefl_0" geometry={nodes.Bushesefl_ShrubsRefl_0.geometry} material={materials.ShrubsRefl} />
                </group>
                <group name="ReflectionsTop" rotation={[-Math.PI / 2, 0, Math.PI]} scale={-100}>
                  <mesh name="3" geometry={nodes['3'].geometry} material={materials.ReflShdr} morphTargetDictionary={nodes['3'].morphTargetDictionary} morphTargetInfluences={nodes['3'].morphTargetInfluences} />
                </group>
                <group name="ReflectionsBottom" rotation={[-Math.PI / 2, 0, Math.PI]} scale={-100}>
                  <mesh name="4" geometry={nodes['4'].geometry} material={materials.ReflShdr} morphTargetDictionary={nodes['4'].morphTargetDictionary} morphTargetInfluences={nodes['4'].morphTargetInfluences} />
                </group>
                <group name="TreeTrunk001" rotation={[-Math.PI / 2, 0, Math.PI]} scale={-100} />
                <group name="TreeAnimRefl" rotation={[-Math.PI / 2, 0, Math.PI]} scale={-100}>
                  <group name="Object_45">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_47" rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-100, 100, 100]} />
                    <group name="Object_107" rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-100, 100, 100]} />
                    <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.TreeTrunkRefl} skeleton={nodes.Object_48.skeleton} />
                    <skinnedMesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.Branch} skeleton={nodes.Object_108.skeleton} />
                  </group>
                </group>
                <group name="TreeBranches001" rotation={[-Math.PI / 2, 0, Math.PI]} scale={-100} />
                <group name="TreeTrunk" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="TreeAnim" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_112">
                    <primitive object={nodes._rootJoint_1} />
                    <group name="Object_114" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_174" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_115" geometry={nodes.Object_115.geometry} material={materials.TreeTrunk} skeleton={nodes.Object_115.skeleton} />
                    <skinnedMesh name="Object_175" geometry={nodes.Object_175.geometry} material={materials.Branch} skeleton={nodes.Object_175.skeleton} />
                  </group>
                </group>
                <group name="TreeBranches" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="GrassOk" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="5" geometry={nodes['5'].geometry} material={materials.Grass} morphTargetDictionary={nodes['5'].morphTargetDictionary} morphTargetInfluences={nodes['5'].morphTargetInfluences} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
export default House;
useGLTF.preload('/model/house.glb')
