/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\model\knightFighting.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const KnightFighting = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/model/knightFighting.glb");
  const { actions,names } = useAnimations(animations, group);
  useEffect(() => {
    actions[names[0]].reset().fadeIn(0.5).play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Sketchfab_model"
          position={[0.043, 0.063, -1.381]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.179}
        >
          <group name="Knight_AniFBX" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <group
                    name="IK_Chain001"
                    position={[-0.93, 0.546, -1.715]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <group
                    name="IK_Chain002"
                    position={[1.09, 0.562, 0.256]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <group name="Point001" position={[-10.729, 2.861, 9.238]} />
                  <group
                    name="Point002"
                    position={[-9.513, 2.107, 8.036]}
                    rotation={[-Math.PI, 0, 0]}
                    scale={-1}
                  />
                  <primitive object={nodes._rootJoint} />
                  <group name="Group54561" rotation={[-Math.PI / 2, 0, 0]} />
                  <group
                    name="Object_6"
                    position={[0, 8.292, -0.45]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials["default"]}
                    skeleton={nodes.Object_7.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
        <group
          name="Sketchfab_model001"
          position={[-0.114, 0.107, 1.204]}
          rotation={[-1.451, 0.145, -3.04]}
          scale={0.175}
        >
          <group name="Knight_AniFBX001" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2001">
              <group name="RootNode001">
                <group name="Object_4001">
                  <group
                    name="IK_Chain001001"
                    position={[-0.93, 0.546, -1.715]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <group
                    name="IK_Chain002001"
                    position={[1.09, 0.562, 0.256]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={0.1}
                  />
                  <group
                    name="Point001001"
                    position={[-10.729, 2.861, 9.238]}
                  />
                  <group
                    name="Point002001"
                    position={[-9.513, 2.107, 8.036]}
                    rotation={[Math.PI, 0, 0]}
                    scale={-1}
                  />
                  <primitive object={nodes._rootJoint_1} />
                  <group name="Group54561001" rotation={[-Math.PI / 2, 0, 0]} />
                  <group
                    name="Object_6001"
                    position={[0, 8.292, -0.45]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  />
                  <skinnedMesh
                    name="Object_7001"
                    geometry={nodes.Object_7001.geometry}
                    material={materials["default.001"]}
                    skeleton={nodes.Object_7001.skeleton}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};
export default KnightFighting;
useGLTF.preload("/model/knightFighting.glb");
