/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\model\pawns.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Pawn=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model/pawns.glb')
  const { actions,names } = useAnimations(animations, group)
  useEffect(() => {
    actions[names[0]].play();
    actions[names[1]].play();
    actions[names[2]].play();
  }, []);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="uploads_files_948873_Pawn" geometry={nodes.uploads_files_948873_Pawn.geometry} material={nodes.uploads_files_948873_Pawn.material} position={[-10, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.164} />
        <mesh name="uploads_files_948873_Pawn001" geometry={nodes.uploads_files_948873_Pawn001.geometry} material={materials['Material.001']} position={[10, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.164} />
        <mesh name="uploads_files_948873_Pawn002" geometry={nodes.uploads_files_948873_Pawn002.geometry} material={nodes.uploads_files_948873_Pawn002.material} rotation={[1.689, 0, 0]} scale={0.021} />
      </group>
    </group>
  )
}
export default Pawn;
useGLTF.preload('/model/pawns.glb')
