/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/model/Plane.glb 
Author: Sketchfab (https://sketchfab.com/Sketchfab)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/sketchfab-5-million-members-f2615549f73946baa65d35fbcf9ee884
Title: Sketchfab 5 Million Members
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Plane=(props) =>{
  const { nodes, materials } = useGLTF('/model/Plane.glb')
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.067}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-2.431, -0.007, 0.002]} rotation={[2.093, 0, 0]}>
            <mesh geometry={nodes.Object_11.geometry} material={materials.Bits} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Wind} />
          </group>
          <group position={[1.947, -0.248, -0.058]} rotation={[1.558, -0.031, 0.006]}>
            <group position={[3.197, 0.079, 0.07]} rotation={[-2.924, -1.547, -2.903]}>
              <primitive object={nodes.GLTF_created_0_rootJoint} />
              <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.Bits} skeleton={nodes.Object_31.skeleton} />
            </group>
            <mesh geometry={nodes.Object_33.geometry} material={materials.Bits} />
          </group>
          <group rotation={[1.57, 0, 0]}>
            <group position={[-0.72, -0.003, -0.04]}>
              <mesh geometry={nodes.Object_45.geometry} material={materials.Bits} rotation={[-0.001, -0.001, -0.001]} />
              <group rotation={[-0.001, -0.001, -0.001]}>
                <mesh geometry={nodes.Object_48.geometry} material={materials.Body} />
                <mesh geometry={nodes.Object_50.geometry} material={materials.Wind} />
              </group>
              <group rotation={[-0.001, -0.001, -0.001]}>
                <mesh geometry={nodes.Object_53.geometry} material={materials.Body} />
                <mesh geometry={nodes.Object_55.geometry} material={materials.Wind} />
              </group>
              <mesh geometry={nodes.Object_38.geometry} material={materials.Bits} />
              <mesh geometry={nodes.Object_40.geometry} material={materials.Body} />
              <mesh geometry={nodes.Object_42.geometry} material={materials.Window} />
            </group>
          </group>
          <mesh geometry={nodes.Object_58.geometry} material={materials.Body} position={[2.078, 0.532, -0.008]} rotation={[1.57, 0, 0.007]} />
          <group position={[-0.663, 0.964, -1.853]} rotation={[1.57, 0.013, 0]}>
            <mesh geometry={nodes.Object_61.geometry} material={materials.Bits} />
            <mesh geometry={nodes.Object_63.geometry} material={materials.Wind} />
          </group>
          <group position={[-0.656, 0.969, 1.836]} rotation={[1.57, 0, 0]}>
            <mesh geometry={nodes.Object_66.geometry} material={materials.Bits} />
            <mesh geometry={nodes.Object_68.geometry} material={materials.Wind} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Wind} position={[-39.945, 0.002, -5.266]} scale={0} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Wind} position={[-39.953, 4.091, 0]} scale={0} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Wind} position={[-39.936, -2.723, 2.357]} scale={0} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.Clouds} position={[-39.874, -2.228, -18.549]} scale={0} />
          <mesh geometry={nodes.Object_72.geometry} material={materials.Clouds} position={[-40.882, 13.846, 18.801]} scale={0} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.Clouds} position={[-39.952, -21.126, -0.644]} scale={0} />
        </group>
      </group>
    </group>
  )
}
export default Plane;
useGLTF.preload('/model/Plane.glb')
