/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ./public/model/Planes.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const FlyingPlane=(props)=> {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model/Planes.glb')
  const { actions,names } = useAnimations(animations, group)
  useEffect(() => {
    actions[names[1]].reset().fadeIn().play();
  }, [actions, names]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.067}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Banner_holder_20_22" position={[1.947, -0.248, -0.058]} rotation={[1.558, -0.031, 0.006]} >
                <group name="Armature_19_20" position={[3.197, 0.079, 0.07]} rotation={[3.924, 1.547, -2.903]} >
                  <group name="GLTF_created_0_19">
                    <group name="Armature_0_16">
                      <group name="GLTF_created_0">
                        <group name="Object_24_18_correction">
                          <group name="Object_24_18" />
                        </group>
                        <primitive object={nodes.GLTF_created_0_rootJoint} />
                        <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry}  material={materials.Bits} skeleton={nodes.Object_31.skeleton} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Object_19_21">
                  <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Bits} />
                </group>
              </group>
              <group name="Cloud_2_45" position={[-39.874, -2.228, -18.549]} scale={0}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.Clouds} position={[32768, -2048.002, 0]} />
              </group>
              <group name="Move_Banner_21_23" position={[1.943, -0.247, -0.059]} rotation={[1.561, 0.047, -0.002]} />
              <group name="Move_Plane_26_36" rotation={[1.57, 0, 0]}>
                <group name="Body_25_35" position={[-0.72, -0.003, -0.04]}>
                  <group name="Object_36_24">
                    <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.Bits} />
                  </group>
                  <group name="Object_37_25">
                    <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.Body} />
                  </group>
                  <group name="Object_38_26">
                    <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.Window} />
                  </group>
                  <group name="Straps_22_28" rotation={[-0.001, -0.001, -0.001]}>
                    <group name="Object_40_27">
                      <mesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Bits} />
                    </group>
                  </group>
                  <group name="Wheels_23_31" rotation={[-0.001, -0.001, -0.001]}>
                    <group name="Object_42_29">
                      <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.Body} />
                    </group>
                    <group name="Object_43_30">
                      <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.Wind} />
                    </group>
                  </group>
                  <group name="Wings_24_34" rotation={[-0.001, -0.001, -0.001]}>
                    <group name="Object_45_32">
                      <mesh name="Object_53" geometry={nodes.Object_53.geometry} material={materials.Body} />
                    </group>
                    <group name="Object_46_33">
                      <mesh name="Object_55" geometry={nodes.Object_55.geometry} material={materials.Wind} />
                    </group>
                  </group>
                </group>
              </group>
              <group name="Propeller_9_6" position={[-2.431, -0.007, 0.002]} rotation={[2.093, 0, 0]}>
                <group name="Object_16_4">
                  <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Bits} rotation={[0.174, 0.017, 0.029]} />
                </group>
                <group name="Object_17_5">
                  <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.Wind} />
                </group>
              </group>
              <group name="Tail_27_38" position={[2.078, 0.532, -0.008]} rotation={[1.57, 0, 0.007]}>
                <group name="Object_48_37">
                  <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Body} />
                </group>
              </group>
              <group name="Wind_1_1" position={[-39.945, 0.002, -5.266]} scale={0}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Wind} position={[32768, -0.001, -4096]} />
              </group>
              <group name="Wings001_28_41" position={[-0.663, 0.964, -1.853]} rotation={[1.57, 0.013, 0]}>
                <group name="Object_50_39">
                  <mesh name="Object_61" geometry={nodes.Object_61.geometry} material={materials.Bits} />
                </group>
                <group name="Object_51_40">
                  <mesh name="Object_63" geometry={nodes.Object_63.geometry} material={materials.Wind} />
                </group>
              </group>
              <group name="Wings002_29_44" position={[-0.656, 0.969, 1.836]} rotation={[1.57, 0, 0]}>
                <group name="Object_53_42">
                  <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.Bits} />
                </group>
                <group name="Object_54_43">
                  <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.Wind} />
                </group>
              </group>
              <group name="Cloud_1_47" position={[-39.952, -21.126, -0.644]} scale={0}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.Clouds} position={[0, 0, 0.003]} />
              </group>
              <group name="Cloud_3_46" position={[-40.882, 13.846, 18.801]} scale={0}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.Clouds} position={[32768, 0.003, -0.002]} />
              </group>
              <group name="Wind_2_2" position={[-39.953, 4.091, 0]} scale={0}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Wind} position={[32768, 0, 0]} />
              </group>
              <group name="Wind_3_3" position={[-39.936, -2.723, 2.357]} scale={0}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Wind} position={[32768, 0, 0]} />
              </group> 
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}
export default FlyingPlane;
useGLTF.preload('/model/Planes.glb')
